Fix openshift-cli tool
When calling the `openshift-cli` MCP tool we'll get the following error:

```
FileNotFoundError: [Errno 2] No such file or directory: 'oc'
```

This is caused by the `PATH` environmental variable no longer including
path `opt/app-root/bin`, which is where we are placing the `oc` binary.

This commit solves this by just moving the `oc` binary to
`/usr/local/bin`.